# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tWP7KMpk-I8Q4CwxDF7r_O46NkznT3Ye
"""

-- Example dataset: housing-like data
CREATE TABLE housing (
    id SERIAL PRIMARY KEY,
    rooms INT,
    sqft INT,
    age INT,
    price FLOAT
);

-- Insert synthetic rows (~1M for demo; scale down if laptop is slow)
INSERT INTO housing (rooms, sqft, age, price)
SELECT
    (random()*5)::INT + 1,
    (random()*2000)::INT + 300,
    (random()*50)::INT,
    (random()*200000 + 50000)::INT
FROM generate_series(1, 1000000);